# pytest.ini
[pytest]
addopts = -q -rs --timeout=2
testpaths = vorpy/tests
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
filterwarnings =
    ignore::numba.core.errors.NumbaPendingDeprecationWarning
