"""Interface selection and network-resolution window for the VorPy GUI.

This module intentionally keeps interface-specific GUI and network checks out of
vorpy_gui.py, Group, and System.
"""

from itertools import combinations
import tkinter as tk
from tkinter import ttk, messagebox


SPECIAL_FIRST = "(default)"
SPECIAL_SECOND = ("surrounding", "solvent")


def group_name(group):
    """Return a display name for either a Group object or a string."""
    if isinstance(group, str):
        return group
    return getattr(group, "name", str(group))


def get_groups(system):
    """Return the currently available concrete Group objects."""
    return [group for group in (getattr(system, "groups", None) or []) if not isinstance(group, str)]


def get_group_names(system):
    """Return unique group names while preserving system order."""
    names = []
    for group in getattr(system, "groups", None) or []:
        name = group_name(group)
        if name and name not in names:
            names.append(name)
    return names


def find_group(system, name):
    """Find a concrete Group object by name."""
    for group in get_groups(system):
        if getattr(group, "name", None) == name:
            return group
    return None


def network_is_constructed(group):
    """Return True only when a Group appears to contain usable network results.

    A non-None ``group.net`` is not sufficient because Group.make_net() creates
    an empty Network object before Network.build() is called. This check remains
    local to the interface module and requires no Group or Network changes.
    """
    if group is None:
        return False

    net = getattr(group, "net", None)
    if net is None:
        return False

    if getattr(net, "loaded_from_logs", False):
        return True

    # Respect a build flag if Network already exposes one now or in the future.
    for attr in ("built", "is_built", "constructed", "network_built"):
        value = getattr(net, attr, None)
        if isinstance(value, bool) and value:
            return True

    # Fall back to topology generated by a completed build. Attribute names are
    # intentionally broad so this remains compatible with current VorPy objects.
    for attr in ("surfs", "edges", "verts"):
        topology = getattr(net, attr, None)
        if topology is None:
            continue
        try:
            if len(topology) > 0:
                return True
        except TypeError:
            pass

    return False


def build_all_pairs(group_names):
    """Apply the requested rules for the dialog's All action."""
    if len(group_names) == 0:
        return [(SPECIAL_FIRST, "surrounding")]
    if len(group_names) == 1:
        return [(group_names[0], "surrounding")]
    if len(group_names) == 2:
        return [(group_names[0], group_names[1])]
    return list(combinations(group_names, 2))


class InterfaceWindow(tk.Toplevel):
    """Dialog that selects interface pairs and resolves a usable source network."""

    def __init__(self, parent, system, fonts=None, build_group=None, calculate_interface=None):
        super().__init__(parent)
        self.parent = parent
        self.system = system
        self.fonts = fonts or {}
        self.build_group = build_group
        self.calculate_interface = calculate_interface
        self.results = []

        self.title("Interface")
        self.resizable(False, False)
        self.transient(parent)
        self.grab_set()

        self._create_widgets()
        self.protocol("WM_DELETE_WINDOW", self.destroy)
        self._center()

    def _font(self, key, fallback):
        return self.fonts.get(key, fallback)

    def _create_widgets(self):
        frame = ttk.Frame(self, padding=18)
        frame.grid(row=0, column=0, sticky="nsew")

        ttk.Label(
            frame,
            text="Interface",
            font=self._font("class 1", ("Arial", 16)),
        ).grid(row=0, column=0, columnspan=3, pady=(0, 3))

        ttk.Label(
            frame,
            text="Select groups for interface",
            font=self._font("class 2", ("Arial", 10)),
        ).grid(row=1, column=0, columnspan=3, pady=(0, 14))

        self.group_names = get_group_names(self.system)
        first_options = list(dict.fromkeys([SPECIAL_FIRST, *self.group_names]))
        second_options = list(dict.fromkeys([*SPECIAL_SECOND, *self.group_names]))

        self.first_var = tk.StringVar(value=first_options[0])
        self.second_var = tk.StringVar(value=second_options[0])

        ttk.Combobox(
            frame,
            textvariable=self.first_var,
            values=first_options,
            state="readonly",
            width=24,
        ).grid(row=2, column=0, padx=(0, 6), sticky="ew")

        ttk.Combobox(
            frame,
            textvariable=self.second_var,
            values=second_options,
            state="readonly",
            width=24,
        ).grid(row=2, column=1, columnspan=2, padx=(6, 0), sticky="ew")

        ttk.Label(
            frame,
            text="Create Interface(s)",
            font=self._font("class 3", ("Arial", 12, "bold")),
        ).grid(row=3, column=0, columnspan=3, pady=(18, 8))

        ttk.Button(frame, text="Cancel", command=self.destroy).grid(row=4, column=0, sticky="w")
        ttk.Button(frame, text="All", command=self._create_all).grid(row=4, column=1, padx=6)
        ttk.Button(frame, text="Selected", command=self._create_selected).grid(row=4, column=2, sticky="e")

        for column in range(3):
            frame.grid_columnconfigure(column, weight=1)

    def _create_selected(self):
        first = self.first_var.get()
        second = self.second_var.get()

        if first == second:
            messagebox.showwarning(
                "Invalid Interface",
                "The two interface selections must be different.",
                parent=self,
            )
            return

        self._process_pairs([(first, second)])

    def _create_all(self):
        self._process_pairs(build_all_pairs(self.group_names))

    def _resolve_source_group(self, first_name, second_name):
        """Return one selected group whose network can supply the interface.

        If neither selected concrete group is constructed, ``build_group`` is
        called for the first concrete group. That callback can be the main GUI's
        existing ``run_group`` method, so construction logic remains unchanged.
        """
        first = find_group(self.system, first_name)
        second = find_group(self.system, second_name)

        if network_is_constructed(first):
            return first
        if network_is_constructed(second):
            return second

        candidate_name = first_name if first is not None else second_name if second is not None else None
        if candidate_name is None:
            return None

        if self.build_group is None:
            raise RuntimeError(
                f"Neither '{first_name}' nor '{second_name}' has a constructed network, "
                "and no group-building callback was supplied."
            )

        built_group = self.build_group(candidate_name)
        if not network_is_constructed(built_group):
            raise RuntimeError(f"The network for group '{candidate_name}' was not constructed successfully.")
        return built_group

    def _process_pairs(self, pairs):
        try:
            results = []
            for first_name, second_name in pairs:
                source_group = self._resolve_source_group(first_name, second_name)

                request = {
                    "group_1": first_name,
                    "group_2": second_name,
                    "source_group": source_group,
                    "source_network": getattr(source_group, "net", None),
                }

                if self.calculate_interface is not None:
                    result = self.calculate_interface(request)
                else:
                    # Temporary handoff object until the actual surface-filtering
                    # function is connected.
                    result = request

                results.append(result)
                source_name = getattr(source_group, "name", "system/default")
                print(f"Interface {first_name} <-> {second_name}; source network: {source_name}")

            self.results = results
            self.destroy()

        except Exception as exc:
            messagebox.showerror("Interface Error", str(exc), parent=self)

    def _center(self):
        self.update_idletasks()
        x = self.parent.winfo_rootx() + (self.parent.winfo_width() - self.winfo_width()) // 2
        y = self.parent.winfo_rooty() + (self.parent.winfo_height() - self.winfo_height()) // 2
        self.geometry(f"+{x}+{y}")


def open_interface_window(parent, system, fonts=None, build_group=None, calculate_interface=None):
    """Open the interface dialog and return the window object."""
    return InterfaceWindow(
        parent=parent,
        system=system,
        fonts=fonts,
        build_group=build_group,
        calculate_interface=calculate_interface,
    )