import numpy as np
import pytest
from types import SimpleNamespace
import pandas as pd

from vorpy.src.calculations.edge_geometry import LineEdgeGeometry
from vorpy.src.calculations.vertex_geometry import (
    intrinsic_corner_angle,
    angular_defect,
    outward_edge_tangent_at_vertex,
    analytic_edge_tangent_away_from_network_vertex,
    spherical_triangle_area,
    aw_cell_surface_normal_at_vertex,
    aw_vertex_cell_surface_normal,
    aw_cell_vertex_gauss_map_normals,
)
from vorpy.src.calculations.vertex_geometry import (
    aw_cell_vertex_surface_cycle,
    orient_aw_cell_vertex_surface_cycle,
    aw_cell_vertex_gauss_map_area,
)


def test_cube_vertex_has_pi_over_two_angular_defect():
    angles = [
        np.pi / 2.0,
        np.pi / 2.0,
        np.pi / 2.0,
    ]

    defect = angular_defect(angles)

    assert defect == pytest.approx(
        np.pi / 2.0,
        abs=1e-14,
    )


def test_cube_complete_gaussian_curvature_is_four_pi():
    defect = angular_defect([
        np.pi / 2.0,
        np.pi / 2.0,
        np.pi / 2.0,
    ])

    total = 8.0 * defect

    assert total == pytest.approx(
        4.0 * np.pi,
        abs=1e-13,
    )


def test_flat_vertex_has_zero_angular_defect():
    # Three patches whose intrinsic sectors exactly fill 2*pi.
    angles = [
        2.0 * np.pi / 3.0,
        2.0 * np.pi / 3.0,
        2.0 * np.pi / 3.0,
    ]

    assert angular_defect(angles) == pytest.approx(
        0.0,
        abs=1e-14,
    )


def test_outward_edge_tangent_points_away_from_first_endpoint():
    edge = LineEdgeGeometry(
        [0.0, 0.0, 0.0],
        [2.0, 0.0, 0.0],
    )

    tangent = outward_edge_tangent_at_vertex(edge, 0)

    assert tangent == pytest.approx([1.0, 0.0, 0.0])


def test_outward_edge_tangent_points_away_from_second_endpoint():
    edge = LineEdgeGeometry(
        [0.0, 0.0, 0.0],
        [2.0, 0.0, 0.0],
    )

    tangent = outward_edge_tangent_at_vertex(edge, 1)

    assert tangent == pytest.approx([-1.0, 0.0, 0.0])


def test_equal_radius_aw_cube_vertex_has_pi_over_two_defect():
    """One vertex of the equal-radius AW cubic cell has defect pi/2.

    The central AW cell is generated by a ball at the origin with equal-radius
    neighbors on the positive coordinate axes. At the (+x,+y,+z) cube vertex,
    three planar AW faces meet, each with intrinsic corner angle pi/2.
    """
    side = 4.0
    half = side / 2.0

    vertex = np.array([half, half, half])

    # Three cube edges leaving the (+,+,+) vertex.
    # Their remote endpoints differ along x, y, and z respectively.
    edge_x = LineEdgeGeometry(
        vertex,
        [-half, half, half],
    )
    edge_y = LineEdgeGeometry(
        vertex,
        [half, -half, half],
    )
    edge_z = LineEdgeGeometry(
        vertex,
        [half, half, -half],
    )

    # The common cube vertex is endpoint 0 for all three edges.
    tx = outward_edge_tangent_at_vertex(edge_x, 0)
    ty = outward_edge_tangent_at_vertex(edge_y, 0)
    tz = outward_edge_tangent_at_vertex(edge_z, 0)

    # Each AW face is bounded by a pair of these edges:
    #
    # x = +half face -> y- and z-directed edges
    # y = +half face -> x- and z-directed edges
    # z = +half face -> x- and y-directed edges
    angle_x_face = intrinsic_corner_angle(ty, tz)
    angle_y_face = intrinsic_corner_angle(tx, tz)
    angle_z_face = intrinsic_corner_angle(tx, ty)

    assert angle_x_face == pytest.approx(
        np.pi / 2.0,
        abs=1e-14,
    )
    assert angle_y_face == pytest.approx(
        np.pi / 2.0,
        abs=1e-14,
    )
    assert angle_z_face == pytest.approx(
        np.pi / 2.0,
        abs=1e-14,
    )

    defect = angular_defect([
        angle_x_face,
        angle_y_face,
        angle_z_face,
    ])

    assert defect == pytest.approx(
        np.pi / 2.0,
        abs=1e-14,
    )

def test_network_vertex_tangent_does_not_depend_on_edge_parameter_orientation():
    vertex = np.array([0.0, 0.0, 0.0])

    forward = LineEdgeGeometry(
        [0.0, 0.0, 0.0],
        [2.0, 0.0, 0.0],
    )

    reverse = LineEdgeGeometry(
        [2.0, 0.0, 0.0],
        [0.0, 0.0, 0.0],
    )

    tangent_forward = analytic_edge_tangent_away_from_network_vertex(
        forward,
        vertex,
    )

    tangent_reverse = analytic_edge_tangent_away_from_network_vertex(
        reverse,
        vertex,
    )

    assert tangent_forward == pytest.approx(
        [1.0, 0.0, 0.0],
        abs=1e-14,
    )

    assert tangent_reverse == pytest.approx(
        [1.0, 0.0, 0.0],
        abs=1e-14,
    )


def test_network_vertex_tangent_rejects_point_not_on_edge_endpoint():
    edge = LineEdgeGeometry(
        [0.0, 0.0, 0.0],
        [2.0, 0.0, 0.0],
    )

    with pytest.raises(
        ValueError,
        match="does not match either endpoint",
    ):
        analytic_edge_tangent_away_from_network_vertex(
            edge,
            [1.0, 0.0, 0.0],
        )


def test_spherical_triangle_area_octant():
    area = spherical_triangle_area(
        [1.0, 0.0, 0.0],
        [0.0, 1.0, 0.0],
        [0.0, 0.0, 1.0],
    )

    assert area == pytest.approx(
        0.5 * np.pi,
        abs=1e-12,
    )


def test_spherical_triangle_area_changes_sign_with_orientation():
    forward = spherical_triangle_area(
        [1.0, 0.0, 0.0],
        [0.0, 1.0, 0.0],
        [0.0, 0.0, 1.0],
    )

    reverse = spherical_triangle_area(
        [1.0, 0.0, 0.0],
        [0.0, 0.0, 1.0],
        [0.0, 1.0, 0.0],
    )

    assert reverse == pytest.approx(-forward, abs=1e-12)


def test_spherical_triangle_area_is_rotation_invariant():
    normals = np.array([
        [1.0, 0.0, 0.0],
        [0.0, 1.0, 0.0],
        [0.0, 0.0, 1.0],
    ])

    rotation = np.array([
        [0.0, -1.0, 0.0],
        [1.0,  0.0, 0.0],
        [0.0,  0.0, 1.0],
    ])

    original = spherical_triangle_area(*normals)
    rotated = spherical_triangle_area(*(normals @ rotation.T))

    assert rotated == pytest.approx(original, abs=1e-12)


def test_aw_cell_surface_normal_reverses_between_cells():
    vertex = np.array([1.0, 1.0, 0.0])
    indices = [10, 20]
    locations = np.array([
        [0.0, 0.0, 0.0],
        [2.0, 0.0, 0.0],
    ])

    normal_10 = aw_cell_surface_normal_at_vertex(
        vertex,
        10,
        20,
        indices,
        locations,
    )

    normal_20 = aw_cell_surface_normal_at_vertex(
        vertex,
        20,
        10,
        indices,
        locations,
    )

    assert normal_20 == pytest.approx(-normal_10, abs=1e-12)


def test_aw_cell_surface_normal_is_unit_length():
    normal = aw_cell_surface_normal_at_vertex(
        [1.0, 1.0, 0.0],
        10,
        20,
        [10, 20],
        np.array([
            [0.0, 0.0, 0.0],
            [2.0, 0.0, 0.0],
        ]),
    )

    assert np.linalg.norm(normal) == pytest.approx(1.0, abs=1e-12)


def _make_aw_cube_vertex_network():
    """Minimal (+,+,+) topology of an equal-radius cubic AW cell."""
    from types import SimpleNamespace
    import pandas as pd

    side = 4.0
    half = side / 2.0

    balls = pd.DataFrame({
        "num": [0, 1, 2, 3],
        "loc": [
            np.array([0.0, 0.0, 0.0]),
            np.array([side, 0.0, 0.0]),
            np.array([0.0, side, 0.0]),
            np.array([0.0, 0.0, side]),
        ],
        "rad": [1.0, 1.0, 1.0, 1.0],
    })

    # Surface 0 = +x, surface 1 = +y, surface 2 = +z.
    surfs = pd.DataFrame({
        "balls": [[0, 1], [0, 2], [0, 3]],
        "edges": [[1, 2], [0, 2], [0, 1]],
    })

    # Edge 0: y/z faces, travels in -x.
    # Edge 1: x/z faces, travels in -y.
    # Edge 2: x/y faces, travels in -z.
    edges = pd.DataFrame({
        "balls": [[0, 2, 3], [0, 1, 3], [0, 1, 2]],
        "surfs": [[1, 2], [0, 2], [0, 1]],
        "verts": [[0, 1], [0, 2], [0, 3]],
    })

    verts = pd.DataFrame({
        "loc": [
            np.array([half, half, half]),
            np.array([-half, half, half]),
            np.array([half, -half, half]),
            np.array([half, half, -half]),
        ],
        "balls": [
            [0, 1, 2, 3],
            [0, 2, 3],
            [0, 1, 3],
            [0, 1, 2],
        ],
        "edges": [[0, 1, 2], [0], [1], [2]],
        "surfs": [[2, 0, 1], [1, 2], [0, 2], [0, 1]],
    })

    return SimpleNamespace(
        balls=balls,
        surfs=surfs,
        edges=edges,
        verts=verts,
        settings={"net_type": "aw"},
    )


def test_aw_vertex_cell_surface_normals_for_cubic_cell():
    net = _make_aw_cube_vertex_network()

    nx = aw_vertex_cell_surface_normal(net, 0, 0, 0)
    ny = aw_vertex_cell_surface_normal(net, 0, 0, 1)
    nz = aw_vertex_cell_surface_normal(net, 0, 0, 2)

    assert nx == pytest.approx([1.0, 0.0, 0.0], abs=1e-12)
    assert ny == pytest.approx([0.0, 1.0, 0.0], abs=1e-12)
    assert nz == pytest.approx([0.0, 0.0, 1.0], abs=1e-12)


def test_aw_cell_vertex_gauss_map_normals_collect_cubic_faces():
    net = _make_aw_cube_vertex_network()

    surfaces, normals = aw_cell_vertex_gauss_map_normals(
        net,
        vertex_index=0,
        cell_index=0,
    )

    assert set(surfaces) == {0, 1, 2}
    assert normals.shape == (3, 3)

    normal_by_surface = {
        surface_index: normal
        for surface_index, normal in zip(surfaces, normals)
    }

    assert normal_by_surface[0] == pytest.approx(
        [1.0, 0.0, 0.0],
        abs=1e-12,
    )
    assert normal_by_surface[1] == pytest.approx(
        [0.0, 1.0, 0.0],
        abs=1e-12,
    )
    assert normal_by_surface[2] == pytest.approx(
        [0.0, 0.0, 1.0],
        abs=1e-12,
    )


def test_aw_cube_vertex_gauss_map_area_is_pi_over_two():
    net = _make_aw_cube_vertex_network()

    _, normals = aw_cell_vertex_gauss_map_normals(
        net,
        vertex_index=0,
        cell_index=0,
    )

    area = spherical_triangle_area(
        normals[0],
        normals[1],
        normals[2],
    )

    assert area == pytest.approx(np.pi / 2.0, abs=1e-12)


def test_aw_cube_vertex_surface_cycle_ignores_storage_order():
    net = _make_aw_cube_vertex_network()

    cycle, _ = aw_cell_vertex_surface_cycle(
        net,
        vertex_index=0,
        cell_index=0,
    )

    assert set(cycle) == {0, 1, 2}
    assert len(cycle) == 3


def test_aw_cube_vertex_surface_cycle_follows_shared_edges():
    net = _make_aw_cube_vertex_network()

    cycle, shared_edges = aw_cell_vertex_surface_cycle(net, 0, 0)

    for i, first in enumerate(cycle):
        second = cycle[(i + 1) % len(cycle)]
        assert frozenset((first, second)) in shared_edges


def test_aw_cube_vertex_oriented_gauss_map_area_is_pi_over_two():
    net = _make_aw_cube_vertex_network()
    half = 2.0

    resolved_edges = {
        0: SimpleNamespace(
            geometry=LineEdgeGeometry(
                [half, half, half],
                [-half, half, half],
            )
        ),
        1: SimpleNamespace(
            geometry=LineEdgeGeometry(
                [half, half, half],
                [half, -half, half],
            )
        ),
        2: SimpleNamespace(
            geometry=LineEdgeGeometry(
                [half, half, half],
                [half, half, -half],
            )
        ),
    }

    area = aw_cell_vertex_gauss_map_area(
        net,
        vertex_index=0,
        cell_index=0,
        resolved_edges=resolved_edges,
    )

    assert area == pytest.approx(np.pi / 2.0, abs=1e-12)